language: java
sudo: true

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

jobs:
  include:
  - stage: build with gradle & generate reports
    script:
    - ./gradlew clean build jacocoTestReport coveralls
  - stage: release to maven central
    deploy:
      skip_cleanup: true
      provider: script
      script: "deploy-to-maven-central.sh"
      on:
        branch: master
        tags: true
