language: java
sudo: true

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
- chmod +x gradlew

jobs:
  include:
    - stage: build with gradle & generate reports
      script:
      - ./gradlew clean build jacocoTestReport coveralls
