on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
            - name: Build with gradle & generate reports
              env:
                  COVERALLS_REPO_KEY: ${{ secrets.COVERALLS_REPO_KEY }}
              run: ./gradlew clean build jacocoTestReport coveralls
            - name: Cache build files
              uses: actions/cache@v2
              id: cache-build
              with:
                  path: ./*
                  key: ${{ github.sha }}
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build
        #if: github.ref == 'refs/heads/master'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Retrieve files from cache
              uses: actions/cache@v2
              id: cache-build
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Deploy to maven central
              run: bash ./deploy_to_maven_central.sh
              env:
                  GPG_SECRET: ${{ secrets.SECRETKEYPASSWORD }}
                  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
                  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

